GET http://localhost:8080/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhcGFtZXRoeXN0QGdtYWlsLmNvbSIsImlhdCI6MTcxMjIzNDE4NSwiZXhwIjoxNzEyMjM0MjA1fQ.HU-C1GdQG76UcyQGjPLtm3hRFjZxEzSswJ9iymA0uMc

###

POST http://localhost:8080/auth/signin/
Content-Type: application/json

{
    "email":"wakhiwemathuthu6@gmail.com",
    "password":"wakhiwe"
}

###

POST http://localhost:8080/auth/register/
Content-Type: application/json

{
  "email":"wakhiwemathuthu6@gmail.com",
  "age":18,
  "password":"wakhiwe"
}

###
GET http://localhost:8080/refresh-token/
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhcGFtZXRoeXN0QGdtYWlsLmNvbSIsImlhdCI6MTcxMjIzMzk4MiwiZXhwIjoxNzEyMzIwMzgyfQ.u3f2nxCx1S1hKvJPBXGGwM9Qpb5BjN_w-gWTlXpPIqc"
}