GET http://localhost:8080/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Indha2hpd2VtYXRodXRodTZAZ21haWwuY29tIiwiaWF0IjoxNzEyMjIxOTkxLCJleHAiOjE3MTIyMjIwMTF9.bsx3jtmNer2oKFLvYw5UrxaDd_ngGphSTzZUg7NRoyA

###

POST http://localhost:8080/auth/signin/
Content-Type: application/json

{
    "email":"wakhiwemathuthu6@gmail.com",
    "password":"wakhiwe"
}

###

POST http://localhost:8080/auth/register/
Content-Type: application/json

{
  "email":"wakhiwemathuthu6@gmail.com",
  "age":18,
  "password":"wakhiwe"
}

###
GET http://localhost:8080/refresh-token/
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Indha2hpd2VtYXRodXRodTZAZ21haWwuY29tIiwiaWF0IjoxNzEyMjIxOTcwLCJleHAiOjE3MTIzMDgzNzB9.KOYparnul1BLH3VyAl8fCQybdnZg7gx46DzH0_j6qLQ"
}