GET http://localhost:8080/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Indha2hpd2VtYXRodXRodTZAZ21haWwuY29tIiwiaWF0IjoxNzEyMzMwNTgxLCJleHAiOjE3MTIzMzA2MDF9.G1QyBx3BI1Msbp1N6uweshP3QitQOdkd5lMgbGShZ4Q

###

POST http://localhost:8080/auth/signin/
Content-Type: application/json

{
    "email":"wakhiwemathuthu6@gmail.com",
    "password":"wakhiwe"
}

###

POST http://localhost:8080/auth/register/
Content-Type: application/json

{
  "email":"wakhiwemathuthu6@gmail.com",
  "age":18,
  "password":"wakhiwe"
}

###
GET http://localhost:8080/refresh-token/

###

DELETE http://localhost:8080/logout/
